name: Build and Deploy to Cloudflare

on:
  push:
    branches:
      - main
      - "*"

env:
  # Since there is no ternary expression, the following conditionally sets
  # ENVIRONMENT to dev on a push event and prod on a publish (release) event
  CLOUDFLARE_PAGES_PROJECT: github-actions-demo

jobs:
  pipeline:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      deployments: write
    name: Build and Deploy
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3
      - name: Install Node
        uses: actions/setup-node@v3
        with:
          node-version: 18.7.0
      - name: Create build for dev
        run: |
          npm run build:dev
        shell: bash
      - name: Publish to Cloudflare Pages Project ${{ env.CLOUDFLARE_PAGES_PROJECT }}
        uses: cloudflare/pages-action@1
        with:
          accountId: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}
          apiToken: ${{ secrets.CLOUDFLARE_API_TOKEN }}
          directory: build
          gitHubToken: ${{ secrets.GH_API_KEY }}
          projectName: ${{ env.CLOUDFLARE_PAGES_PROJECT }}
